// IncidentType restricts incident categories to the three types CERP handles
// These match the CHECK constraint in the incidents table in schema.sql
export type IncidentType = "flood" | "fire" | "accident";

// SeverityLevel represents how critical an incident is rated by the admin
// These match the CHECK constraint in the incidents table
export type SeverityLevel = "low" | "moderate" | "critical";

// IncidentStatus tracks which stage of the Kasoa dispatch workflow the incident is in
// These match the CHECK constraint in the incidents table
export type IncidentStatus = "new" | "dispatched" | "resolved";

// UserRole controls what a user is allowed to do on the platform
// citizen: can report incidents and receive alerts
// responder: can view and update incident status
// admin: full access to dispatch, alerts, and the command center
export type UserRole = "citizen" | "responder" | "admin";

// AlertChannel defines the three delivery methods for broadcasting community alerts
export type AlertChannel = "sms" | "push" | "web";

// User represents a row in the users table in the database
export interface User {
  // UUID primary key generated by PostgreSQL
  id: string;
  // Full name entered during registration
  name: string;
  // Email address used to log in
  email: string;
  // Bcrypt hash of the password — never the plaintext
  password_hash: string;
  // Role that controls access permissions
  role: UserRole;
  // The Kasoa community town the user is based in
  region: string | null;
  // When the user account was created
  created_at: Date;
}

// Incident represents a row in the incidents table in the database
export interface Incident {
  // UUID primary key
  id: string;
  // Category of the emergency
  type: IncidentType;
  // Free-text description of what is happening
  description: string;
  // Address or landmark in the Kasoa community
  location_text: string;
  // GPS latitude — null if the citizen declined to share location
  latitude: number | null;
  // GPS longitude — null if the citizen declined to share location
  longitude: number | null;
  // The specific Kasoa community town where the incident occurred
  region: string;
  // How critical the incident has been rated
  severity: SeverityLevel;
  // Current stage in the dispatch workflow
  status: IncidentStatus;
  // Name of the Kasoa agency assigned to respond
  assigned_agency: string | null;
  // UUID of the user who filed the report
  reported_by: string | null;
  // URLs of photos or videos uploaded with the report
  media_urls: string[];
  // When the incident was first reported
  created_at: Date;
  // When the incident record was last modified
  updated_at: Date;
}

// Alert represents a row in the alerts table — a community broadcast message
export interface Alert {
  // UUID primary key
  id: string;
  // Short notification title
  title: string;
  // Full alert message body
  message: string;
  // Which Kasoa town was targeted — "All Kasoa Towns" for community-wide alerts
  target_region: string;
  // Optional geo-fence radius in kilometres
  radius_km: number | null;
  // Array of delivery channels used
  channels: AlertChannel[];
  // UUID of the admin who broadcast this alert
  issued_by: string;
  // When the alert was sent
  created_at: Date;
}

// ResponseLog represents a row in the response_logs table
// Every status change and admin action is recorded here for audit purposes
export interface ResponseLog {
  // UUID primary key
  id: string;
  // Which incident this log entry relates to
  incident_id: string;
  // Which responder or admin performed this action
  responder_id: string;
  // Human-readable description of what was done
  action: string;
  // When this action occurred
  created_at: Date;
}

// JwtPayload defines the data embedded inside each JWT token
// This is decoded by the auth middleware on every protected request
export interface JwtPayload {
  // UUID of the logged-in user
  userId: string;
  // Role of the logged-in user — used for access control checks
  role: UserRole;
  // Email of the logged-in user
  email: string;
}

// Import the Express Request type to extend it with the user property
import { Request } from "express";

// AuthRequest extends the standard Express Request to include the decoded JWT payload
// After the requireAuth middleware runs, req.user is guaranteed to be set
export interface AuthRequest extends Request {
  // The decoded JWT payload attached by the requireAuth middleware
  // Optional because it is not set on unauthenticated routes
  user?: JwtPayload;
}
