// IssueType restricts community issue categories to the ten types CERP handles
// These match the CHECK constraint in the incidents table in schema.sql
export type IssueType =
  | "traffic_congestion"
  | "burst_water_pipe"
  | "electrical_fault"
  | "weak_bridge"
  | "pothole_bad_road"
  | "illegal_dumping"
  | "streetlight_outage"
  | "open_manhole"
  | "noise_complaint"
  | "other";

// SeverityLevel represents how urgent a community issue is rated by the admin
export type SeverityLevel = "low" | "moderate" | "critical";

// IssueStatus tracks which stage of the resolution workflow the issue is in
export type IssueStatus = "new" | "assigned" | "in_progress" | "resolved";

// UserRole controls what a user is allowed to do on the platform
// user: can report community issues and receive notifications
// responder: can view and update issue status on behalf of agencies
// admin: full access to agency assignment, notifications, and the command center
// superadmin: management of users (admins/responders) + all admin capabilities
export type UserRole = "user" | "responder" | "admin" | "superadmin";

// AlertChannel defines the three delivery methods for broadcasting community notifications
export type AlertChannel = "sms" | "push" | "web";

// User represents a row in the users table in the database
export interface User {
  // UUID primary key generated by PostgreSQL
  id: string;
  // Full name entered during registration
  name: string;
  // Email address used to log in
  email: string;
  // Bcrypt hash of the password — never the plaintext
  password_hash: string;
  // Role that controls access permissions
  role: UserRole;
  // The Kasoa community town the user is based in
  region: string | null;
  // When the user account was created
  created_at: Date;
}

// Incident represents a community issue reported by a citizen
export interface Incident {
  // UUID primary key
  id: string;
  // Category of the community issue
  type: IssueType;
  // Free-text description of the issue
  description: string;
  // Address or landmark in the Kasoa community
  location_text: string;
  // GPS latitude — null if the citizen declined to share location
  latitude: number | null;
  // GPS longitude — null if the citizen declined to share location
  longitude: number | null;
  // The specific Kasoa community town where the issue was observed
  region: string;
  // How urgent the issue has been rated
  severity: SeverityLevel;
  // Current stage in the resolution workflow
  status: IssueStatus;
  // Name of the agency assigned to handle the issue
  assigned_agency: string | null;
  // UUID of the user who filed the report
  reported_by: string | null;
  // URLs of photos or videos uploaded with the report
  media_urls: string[];
  // When the issue was first reported
  created_at: Date;
  // When the issue record was last modified
  updated_at: Date;
}

// Alert represents a community broadcast notification
export interface Alert {
  // UUID primary key
  id: string;
  // Short notification title
  title: string;
  // Full notification message body
  message: string;
  // Which Kasoa town was targeted
  target_region: string;
  // Optional geo-fence radius in kilometres
  radius_km: number | null;
  // Array of delivery channels used
  channels: AlertChannel[];
  // UUID of the admin who broadcast this notification
  issued_by: string;
  // When the notification was sent
  created_at: Date;
}

// ResponseLog tracks every action taken on a community issue for audit
export interface ResponseLog {
  // UUID primary key
  id: string;
  // Which community issue this log entry relates to
  incident_id: string;
  // Which responder or admin performed this action
  responder_id: string;
  // Human-readable description of what was done
  action: string;
  // When this action occurred
  created_at: Date;
}

// JwtPayload defines the data embedded inside each JWT token
export interface JwtPayload {
  // UUID of the logged-in user
  userId: string;
  // Role of the logged-in user — used for access control checks
  role: UserRole;
  // Email of the logged-in user
  email: string;
}

// Import the Express Request type to extend it with the user property
import { Request } from "express";

// AuthRequest extends the standard Express Request to include the decoded JWT payload
// After the requireAuth middleware runs, req.user is guaranteed to be set
export interface AuthRequest extends Request {
  // The decoded JWT payload attached by the requireAuth middleware
  // Optional because it is not set on unauthenticated routes
  user?: JwtPayload;
}
